server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/jb-user
  application:
    name: EXPENSE-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost